name: Deploy Application

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup SSH key
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Connect to VM and Deploy
        run: |
          ssh -o StrictHostKeyChecking=no username@vm_ip << 'EOF'
            cd /path/to/your/project
            git pull origin main
            docker build -t myapp .
            docker ps -q -f name=myapp | xargs -r docker stop
            docker ps -q -f name=myapp | xargs -r docker rm
            docker run -d -p 80:80 --name myapp myapp
          EOF